# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8ab2fe3be9363cb2af82e50e8713ffbd6aa01b1d8c2e062cbf2f35a7b7094e5855dfcf16ce9ec92a409658ca555a79d1d6dbe857e6c0f32a4b211ceaf2b9a0f

test:
  secret_key_base: 89f80e760884ede264d372d3aaabc33d19790fa1a8e51d9e961a812b7369888830195c84594d8ae5b1ff9e7d6e8caed12ead640c7a19b4722a73e51f0a3c4a37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
